server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Serve static assets with cache
  location /assets {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  # All routes → index.html (React Router)
  location / {
    try_files $uri $uri/ /index.html;
  }
}
